[tool.poetry]
name = "rpi4-uefi-build"
version = "0.1.0"
description = "EDK2 RPi4 Build Workspace using Stuart and Poetry"
authors = ["User <user@example.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
edk2-pytool-library = "^0.23.10"
edk2-pytool-extensions = "^0.27.0"
setuptools = "^78.1.1"
# edk2-basetools is optional but recommended
edk2-basetools = "^0.1.0"
regex = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
